# btop configuration
# See also: configs/btop/themes/carbon.theme

color_theme = "$HOME/.config/btop/themes/carbon.theme"
theme_background = True
true_color = True
rounded_corners = False
graph_symbol = "braille"
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default"
update_ms = 1500
