# Arrow — minimal arrow prompt
# user@hostname ~/path ❯

palette = "theme"

add_newline = true
scan_timeout = 10
command_timeout = 100

format = "$username$hostname$directory$character"

[username]
show_always = true
style_user = "bold fg"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold ok_dim"
format = "@[$hostname]($style)"

[directory]
style = "bold dir"
truncate_to_repo = true
truncation_length = 3
format = " [$path]($style) "

[character]
success_symbol = "[❯](bold ok) "
error_symbol = "[❯](bold error) "
vimcmd_symbol = "[❮](bold ok) "

[git_branch]
disabled = true
[git_status]
disabled = true
[golang]
disabled = true
[java]
disabled = true
[python]
disabled = true
[docker_context]
disabled = true
[kubernetes]
disabled = true
[aws]
disabled = true
[cmd_duration]
disabled = true
[memory_usage]
disabled = true
